### PR TITLE
login and registration added

### PR DESCRIPTION
**Pull request by WilsonTBell**
Got the login function working as well as adding the ability to register as a new user

test: serve the site, register as a new user, and then login

### CODE REVIEW

**Comment by rjdny** [comment]
👍

**Review by rjdny — APPROVED** [review]

**Comment by SAS7178** [comment]
👍🏼

**Comment by SAS7178** [comment]
⚡

**Comment by SAS7178** [comment]
😄

**Comment by SAS7178** [comment]
🥾

**Comment by SAS7178** [comment]
🌡️

**Comment by SAS7178** [comment]
🤒

**Comment by SAS7178** [comment]
🧵

**Comment by SAS7178** [comment]
🪜

**Comment by crate1011** [comment]
🇹🇭

**Pull request merged**
